apiVersion: v1
kind: Service
metadata:
  name: cloudnativebasicspring-service
  namespace: k8-booster
  labels:
    app: cloudnativebasicspring
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloudnativebasicspring
  type: LoadBalancer
