name: Demo for OKE Serverless
run-name: ${{ github.actor }} is testing out GitHub Actions with OCI🚀 OKE Serverless
on: [workflow_dispatch]
env:
  # Setting an environment variable with the value of a configuration variable
  OCI_CLI_REGION:  ${{ vars.VAR_OCI_CLI_REGION }}
jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Play with OKE Serverless
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      #OCI_CLI_REGION: ${{ vars.VAR_OCI_CLI_REGION }}
      
      OCIR_TOKEN: ${{ secrets.OCIR_TOKEN }}
      OCIR_USERNAME: ${{ secrets.OCIR_USERNAME }}
      OKE_CLUSTER_OCID: ${{ secrets.OKE_CLUSTER_OCID }}
      REGISTRY: fra.ocir.io
      IMAGE_NAME: ${{ github.repository }}
      OCI_COMPARTMENT_ID: ocid1.compartment.oc1..aaaaaaaak3cg7aoegjmd7pcpv6j6uhcmssa3ghygxjamzbtas7fx7qauahga
      #VAR_OCI_CLI_REGION: ${{ vars.VAR_OCI_CLI_REGION }}

      
    steps:
    
      - name: "Checkout Rep"   
        uses: actions/checkout@v3
    
      - name: "list workspace"
        run: ls -ltra
        shell: bash
      
      - name: "Get Cluster details"
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: 'ce cluster get --cluster-id ${{ secrets.OKE_CLUSTER_OCID }}'
          silent: False
     
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
      
      - name: Get Nodes
        run: kubectl get nodes -A
      
      - name: Create k8booster Namespace
        run: kubectl apply -f .github/workflows/k8booster/manifest-namespace.json
      
      - name: Deploy Dummy App
        run: kubectl apply -f .github/workflows/k8booster/manifest-deploy.yml
        
      - name: Check Dummy App
        run: kubectl get -f .github/workflows/k8booster/manifest-deploy.yml -o wide
        
        
        
        

      





