name: GitHub Actions OCI Demo
run-name: ${{ github.actor }} is testing out GitHub Actions with OCI🚀
on: [workflow_dispatch]
jobs:
  - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='testing'].id"
  
