name: GitHub Actions OCI Demo
run-name: ${{ github.actor }} is testing out GitHub Actions with OCI🚀
on: [workflow_dispatch]
jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: List the display name and shape of the instances in my compartment
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='functions'].id"
          silent: False
      - name: Retrieve the display name and shape of the instances in my compartment
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-instances
        with:
          command: 'compute instance list --compartment-id ${{ steps.find-compartment-id.outputs.raw_output }}'
          query: 'data[*].{name: \"display-name\", shape: shape}'
      - name: Retrieve the display name of the applications for functions in my compartment
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-applications
        with:
          command: 'fn application list --compartment-id ${{ steps.find-compartment-id.outputs.raw_output }}'
          query: 'data[*].{name: \"display-name\", applicationId: \"id\" }'
          silent: False
      - name: Retrieve the id for functions in my application
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-applications-id
        with:
          command: 'fn function list --application-id ocid1.fnapp.oc1.eu-frankfurt-1.aaaaaaaaj4dgig5nut2su5tjvo3faum5npzr5yhoweid4q4p2r2esmzn222q'
          query: 'data[*].{name: \"display-name\", functionId: \"id\" }'
          silent: False
      - name: Invoke function in my application
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        #id: functions-response
        with:
          command: 'fn function invoke --function-id "ocid1.fnfunc.oc1.eu-frankfurt-1.aaaaaaaaniupaauxysoxzmltd7r2vrrk5mlgxeldaiaexeinbyqg7tbrwwzq" --file "-" --body "john"'
          #query: 'data[*].{name: \"display-name\", functionId: \"id\" }'
          #fernandoharris: Change returning type of my hello world to JSON should solve the issue!
          silent: False     
